#!/usr/bin/env sh
# Reads .env and writes assets/js/supabase-config.js with window.LUTSITE_* globals.
# Safe to run when .env is missing — falls back to 'TODO' for each variable.
# Quote-escapes single quotes so values containing ' are valid JS string literals.

set -eu

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
ENV_FILE="$ROOT_DIR/.env"
OUT_FILE="$ROOT_DIR/assets/js/supabase-config.js"

VARS="SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_EDGE_FUNCTION TURNSTILE_SITE_KEY"

get_value() {
  var_name=$1
  if [ ! -f "$ENV_FILE" ]; then
    echo "TODO"
    return
  fi
  line=$(grep -E "^${var_name}=" "$ENV_FILE" | head -n 1 || true)
  if [ -z "$line" ]; then
    echo "TODO"
    return
  fi
  val=${line#*=}
  # Strip surrounding single or double quotes
  val=${val#\"}
  val=${val%\"}
  val=${val#\'}
  val=${val%\'}
  echo "$val"
}

escape_single_quotes() {
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
}

mkdir -p "$(dirname "$OUT_FILE")"

{
  echo "/* AUTO-GENERATED by script/build-config.sh — do not edit by hand. */"
  if [ ! -f "$ENV_FILE" ]; then
    echo "/* .env missing — falling back to TODO placeholders. */"
  fi
  for var in $VARS; do
    raw=$(get_value "$var")
    esc=$(escape_single_quotes "$raw")
    # Map SUPABASE_URL -> LUTSITE_SUPABASE_URL etc.
    case "$var" in
      SUPABASE_URL)             key=LUTSITE_SUPABASE_URL ;;
      SUPABASE_ANON_KEY)        key=LUTSITE_SUPABASE_ANON_KEY ;;
      SUPABASE_EDGE_FUNCTION)   key=LUTSITE_SUPABASE_EDGE_FUNCTION ;;
      TURNSTILE_SITE_KEY)       key=LUTSITE_TURNSTILE_SITE_KEY ;;
    esac
    echo "window.$key = '$esc';"
  done
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
